name: Run Unit Tests for Battleships

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.410'  # Adjust if using a different .NET version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Run Unit Tests
      run: dotnet test --verbosity normal
